services:

  api:
    build:
      context: .
      dockerfile: src/workflow_lab/api/Dockerfile
    container_name: workflow_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - workflow-network

  app:
    build:
      context: .
      dockerfile: src/workflow_lab/ui/Dockerfile
    container_name: workflow_app
    environment:
      - URL_PREFIX=http://api:8000/api/v1

    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - workflow-network
    depends_on:
      - api

  prometheus:
    image: dhi.io/prometheus:3.11
    container_name: workflow_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - workflow-network
    depends_on:
      - api

  grafana:
    image: dhi.io/grafana:13-debian13-dev
    container_name: workflow_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    networks:
      - workflow-network
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  workflow-network:
    driver: bridge
