[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "workflow-lab"
version = "0.1.0"
description = "Experimenting with workflows in a production-like environment"
readme = "README.md"
requires-python = ">=3.12,<3.15"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
  { name="babaksoft", email="babak.eslamieh@gmail.com" },
]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "arize-phoenix",
    "fastapi[standard]",
    "llama-index-llms-bedrock",
    "llama-index-llms-ollama",
    "llama-index-llms-openai",
    "llama-index-workflows",
    "openinference-instrumentation-llama-index",
    "prometheus_client",
    "pydantic",
    "python-dotenv",
]

[project.urls]
Homepage = "https://github.com/babaksoft/workflow-lab"
Issues = "https://github.com/babaksoft/workflow-lab/issues"

[project.optional-dependencies]
build = [
    "build",
    "hatchling"
]

ui = [
    "requests",
    "streamlit",
]

dev = [
    "black",
    "isort",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "ruff",
    "streamlit",
]

[tool.black]
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
asyncio_mode = "auto"

[tool.hatch.build.targets.wheel]
packages = ["src/workflow_lab"]
